# Generated by Django 4.1.5 on 2023-01-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Question Title')),
                ('degree', models.DecimalField(decimal_places=2, max_digits=5)),
                ('technique', models.CharField(choices=[('MultipleChoices', 'MultipleChoices'), ('Complete', 'Complete'), ('Essay', 'Essay')], max_length=50, verbose_name='Question Type')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50, verbose_name='Question Dificulty')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Quize', max_length=200, verbose_name='Quize Title')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('ends_on', models.DateTimeField(verbose_name='Ends On')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='quize.question', verbose_name='Question Name')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quize_questions', to='quize.quiz', verbose_name='Quize Title'),
        ),
    ]
