# Generated by Django 4.1.5 on 2023-01-08 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_alter_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quize',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quize.quiz', verbose_name='Quize Title'),
            preserve_default=False,
        ),
    ]
